version: '3.7'

services:

  django:
    build:
      context: .
      dockerfile: docker/python/Dockerfile

    entrypoint: /scripts/web_entrypoint.sh

    command: gunicorn -w 4 sNeeds.wsgi -b 0.0.0.0:8000

    environment:
      SECRET_KEY: temp_secret_key
      DJANGO_DEPLOYMENT: 1
      #TODO: Make this implemented
      DJANGO_SETTINGS_MODULE: sNeeds.settings.deployment # Used by gunicorn

      #DB config
      DB_NAME: sneeds
      DB_USER: sneeds
      DB_PASSWORD: temp
      DB_HOST_IP: 172.17.0.1
      DB_HOST_PORT: 5432
      SUPERUSER_USERNAME: a@g.com
      SUPERUSER_PASSWORD: 111111

    depends_on:
      - redis

    volumes:
      - ./code:/code
      - static_files:/static_files

    ports:
      - 8000:8000

    tty: true

    networks:
      - backend

  nginx:

    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    networks:
      - backend

    volumes:
      - static_files:/static_files

    depends_on:
      - django

    ports:
      - 8080:80

  redis:
    image: redis:5.0.5-alpine

    container_name: redis

    ports:
      - 6379:6379

    networks:
      - backend

networks:
  backend:

volumes:
  static_files: