version: '3.7'

services:

  django: &django
    build:
      context: .
      dockerfile: docker/python/develop/Dockerfile

    command: bash
    entrypoint: /scripts/web_entrypoint.sh

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEPLOYMENT: 0

      #DB config
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST_IP: ${DB_HOST_IP}
      DB_HOST_PORT: 5432

    depends_on:
      - redis
      - celery

    volumes:
      - ./code:/code

    ports:
      - 9000:8000 #For django
      - 9555:5555 #When flower is up on port 5555

    stdin_open: true
    tty: true

    networks:
      - backend

  celery:
    <<: *django
    command: bash -c "celery -A sNeeds worker --loglevel=info && celery -A sNeeds beat --loglevel=info"
    ports: []
    entrypoint: []
    depends_on:
      - redis

  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:

