version: '3.7'

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./sNeeds/:/usr/src/sNeeds/
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=kjwedkwehfkewhfjk
      - DJANGO_DEPLOYMENT=0