version: '3.7'

services:

  django:
    build:
      context: .
      dockerfile: docker/python/Dockerfile

    entrypoint: /scripts/web_entrypoint.sh

    command: gunicorn -w 4 sNeeds.wsgi -b 0.0.0.0:8000

    environment:
      SECRET_KEY: idjfidfji
      DJANGO_DEPLOYMENT: 0

    volumes:
      - ./code:/code

    ports:
      - 8000:8000

    tty: true

    networks:
      - backend

  nginx:

    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    ports:
      - 80:80

networks:
  backend: