version: '3.7'

services:

  django: &django
    build:
      context: .
      dockerfile: docker/python/Dockerfile

    command: python manage.py runserver 0.0.0.0:8000

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEPLOYMENT: 0

      #DB config
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST_IP: ${DB_HOST_IP}
      DB_HOST_PORT: 5432

    depends_on:
      - redis
      - celery

    volumes:
      - ./code:/code

    ports:
      - 8000:8000

    tty: true

    networks:
      - backend

  celery:
    <<: *django
    command: bash -c "celery -A sNeeds worker --loglevel=info && celery -A sNeeds beat --loglevel=info"
    ports: []
    depends_on:
      - redis

  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:

