version: '3.7'

services:

  django: &django
    build:
      context: .
      dockerfile: docker/python/deploy/Dockerfile

    entrypoint: /scripts/web_entrypoint.sh

    command: gunicorn -w 4 sNeeds.wsgi -b 0.0.0.0:8000

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEPLOYMENT: 1
      #TODO: Make this implemented
      DJANGO_SETTINGS_MODULE: sNeeds.settings.deployment # Used by gunicorn

      #DB config
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST_IP: ${DB_HOST_IP}
      DB_HOST_PORT: 5432

    volumes:
      - ./code:/code
      - static_files:/static_files

    ports:
      - 8000:8000

    networks:
      - backend
      - backend-internal-network

    tty: true

    depends_on:
      - redis
      - celery


  celery:
    <<: *django
    command: bash -c "celery -A sNeeds worker --loglevel=info && celery -A sNeeds beat --loglevel=info"
    ports: []
    entrypoint: []
    depends_on:
      - redis

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    networks:
      - backend
      - backend-internal-network

    volumes:
      - static_files:/static_files

    depends_on:
      - django

    ports:
      - 8080:80

  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
    networks:
      - backend-internal-network

networks:
  backend-internal-network:
    driver: overlay
    internal: true
  backend:

volumes:
  static_files: