version: '3.7'

services:
  web:

    build:
      context: .
      dockerfile: docker/python/Dockerfile

    entrypoint: /scripts/web_entrypoint.sh

    command: python manage.py runserver 0.0.0.0:8000

    environment:
      SECRET_KEY: idjfidfji
      DJANGO_DEPLOYMENT: 0

    volumes:
      - ./code:/code

    ports:
      - 8000:8000

    tty: true

    depends_on:
      - postgres



  postgres:
    image: postgres:11.5

    environment:
      POSTGRE_DB: sneeds
      POSTGRES_USER: sneeds
      POSTGRES_PASSWORD: temp

    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 6543:5432

volumes:
  pgdata:
